# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('difficulty', models.IntegerField(choices=[(1, 'beginner'), (2, 'intermediate'), (3, 'advanced')], default=1)),
                ('intensity', models.IntegerField(choices=[(1, 'low'), (2, 'moderate'), (3, 'high')], default=1)),
            ],
        ),
    ]
