# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 22:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 20, 22, 20, 39, 163903, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='duration',
            field=models.IntegerField(help_text='duration in minutes'),
        ),
    ]
